#
# Module manifest for module 'Ravenhill.UserUtilities'
#
# Generated by: R8V
#
# Generated on: 15-May-22
#

@{

  # Script module or binary module file associated with this manifest.
  RootModule        = 'Ravenhill.UserUtilities.psm1';

  # Version number of this module.
  ModuleVersion     = '1.1'

  # ID used to uniquely identify this module
  GUID              = '7b525f07-ee5e-4301-a82b-ad1300dfa94f'

  # Author of this module
  Author            = 'R8V'

  # Company or vendor of this module
  CompanyName       = 'Ravenhill Studios'

  # Copyright statement for this module
  Copyright         = 'pwsh-fun by R8V is licensed under a Creative Commons Attribution 4.0 ' `
    + 'International License. Based on a work at https://github.com/r8vnhill/pwsh-fun.'

  # Description of the functionality provided by this module
  Description       = 'User utility commands for PowerShell.'

  # Script files (.ps1) that are run in the caller's environment prior to importing this module.
  ScriptsToProcess  = @('UserUtilities.Setup.ps1')

  # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
  FunctionsToExport = @('Set-EnvironmentVariable', 'Set-HomeDirectory', 'Get-HomeDirectory', 
    'Get-EnvironmentVariable')

  # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
  CmdletsToExport   = @()

  # Variables to export from this module
  VariablesToExport = @()

  # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
  AliasesToExport   = @('setenv')

  # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
  PrivateData       = @{
    PSData = @{} # End of PSData hashtable
  } # End of PrivateData hashtable
}

